(define (convert-to-epaper filein fileout)
	(let* ((image (car (gimp-file-load RUN-NONINTERACTIVE filein filein)))
	      (drawable (car (gimp-image-active-drawable image))))
	      	(gimp-context-set-interpolation INTERPOLATION-CUBIC)
		(gimp-image-scale image 600 448)
		(gimp-image-convert-indexed image CONVERT-DITHER-FS CONVERT-PALETTE-CUSTOM 7 FALSE FALSE "Waveshare 7-Color")
		(file-bmp-save RUN-NONINTERACTIVE image drawable fileout fileout)
		(gimp-image-delete image)
	)
)
